[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "wsi-patching"
version = "0.1.0"
description = "High Performance Patching Library for Digital Pathology AI dataset creation."
requires-python = ">=3.9"
authors = [{ name = "Robin van Hoorn", email = "r.d.vanhoorn@amsterdamumc.nl" }]
dependencies = ["numpy", "pandas", "webdataset", "pillow", "torch"]

[project.optional-dependencies]
gpu = ["cucim", "cupy-cuda12x"]

[tool.hatch.build.targets.wheel]
packages = ["src/wsi_patching"]

[tool.hatch.build]
exclude = ["/data", "/output", ".vscode", ".git", "__pycache__"]

[tool.ruff]
line-length = 120
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
docstring-code-format = false
